---
env:
  contexts:
  - name: "skf-labs"
    urls:
    - "http://192.168.68.133:5000"
    includePaths:
    - "http://192.168.68.133:5000.*"
    excludePaths: []
    authentication:
      parameters: {}
      verification:
        method: "response"
        pollFrequency: 60
        pollUnits: "requests"
    sessionManagement:
      method: "cookie"
      parameters: {}
  parameters:
    failOnError: true
    failOnWarning: false
    progressToStdout: true
  vars: {}
jobs:
- parameters:
    maxAlertsPerRule: 0
    scanOnlyInScope: true
    maxBodySizeInBytesToScan: 1
    enableTags: false
  rules: []
  name: "passiveScan-config"
  type: "passiveScan-config"
- parameters:
    action: "add"
    type: "standalone"
    engine: "Zest : Mozilla Zest"
    name: "Credentials-guessing-1"
    file: "/Users/riccardo.tencate/Desktop/skf-labs-zap/zap-tests/zest/Credentials-guessing-1.zst"
  name: "script"
  type: "script"
- parameters:
    action: "run"
    type: "standalone"
    engine: ""
    name: "Credentials-guessing-1"
  name: "script"
  type: "script"
- parameters:
    time: "3"
    fileName: ""
  name: "delay"
  type: "delay"
- parameters:
    template: "traditional-html"
    reportDir: "/Users/riccardo.tencate/Desktop/results"
    reportFile: ""
    reportTitle: "ZAP Scanning Report"
    reportDescription: ""
    displayReport: true
  risks:
  - "low"
  - "medium"
  - "high"
  confidences:
  - "low"
  - "medium"
  - "high"
  - "confirmed"
  name: "report"
  type: "report"

